services:

  #####
  # reverse proxy for the whole environment
  #####
  nginx:
    profiles:
      - dev
    image: nginx:1.29.4-alpine
    network_mode: host
    environment:
      - DEV_HOST=${DEV_HOST}
      - NGINX_PORT1=${NGINX_PORT1}
      - NGINX_PORT2=${NGINX_PORT2}
      - DEV_API_PORT=${DEV_API_PORT}
      - DEV_UI_PORT=${DEV_UI_PORT}
      - SD_PORT=${SD_PORT}
      - DF_PORT=${DF_PORT}
      - EVENTS_PORT=${EVENTS_PORT}
      - OAV_PORT=${OAV_PORT}
    volumes:
      - ./dev/resources/nginx.conf.template:/etc/nginx/templates/default.conf.template:ro

  #####
  # related services from the data-fair stack
  #####

  simple-directory:
    profiles:
      - dev
    image: ghcr.io/data-fair/simple-directory:8
    network_mode: host
    depends_on:
      - mongo
    environment:
      - DEBUG=session
      - PORT=${SD_PORT}
      - CONTACT=contact@test.com
      - ADMINS=["superadmin@test.com","test_superadmin@test.com"]
      - PUBLIC_URL=http://${DEV_HOST}:${NGINX_PORT1}/simple-directory
      - MAILDEV_ACTIVE=true
      - MONGO_URL=mongodb://localhost:${MONGO_PORT}/simple-directory
      - STORAGE_TYPE=file
      - AUTHRATELIMIT_ATTEMPTS=500
      - AUTHRATELIMIT_DURATION=30
      - OBSERVER_ACTIVE=false
      - MANAGE_PARTNERS=true
      - MANAGE_DEPARTMENTS=true
      - CIPHER_PASSWORD=dev
    volumes:
      - ./dev/resources/users.json:/app/data/users.json
      - ./dev/resources/organizations.json:/app/data/organizations.json

  data-fair:
    profiles:
      - dev
    image: ghcr.io/data-fair/data-fair:5
    restart: on-failure:10
    network_mode: host
    depends_on:
      mongo:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    environment:
      - PORT=${DF_PORT}
      - MONGO_URL=mongodb://localhost:${MONGO_PORT}/data-fair
      - ES_HOST=http://localhost:${ES_PORT}
      - DIRECTORY_URL=http://${DEV_HOST}:${NGINX_PORT1}/simple-directory
      - PRIVATE_EVENTS_URL=http://localhost:${EVENTS_PORT}
      - PRIVATE_DIRECTORY_URL=http://localhost:${SD_PORT}
      - PUBLIC_URL=http://${DEV_HOST}:${NGINX_PORT1}/data-fair
      - WS_PUBLIC_URL=ws://${DEV_HOST}:${NGINX_PORT1}/data-fair
      - OBSERVER_ACTIVE=false
      - PRIVATE_PROCESSINGS_URL=http://localhost:${DEV_API_PORT}
      - SECRET_EVENTS=secret-events
      - EXTRA_ADMIN_NAV_ITEMS=[{"id":"processingsAdminDoc","href":"http://${DEV_HOST}:${NGINX_PORT1}/openapi-viewer?urlType=processingsAdmin","icon":"mdi-cog-transfer-outline","title":"API Traitements périodiques"}]
      - OPENAPI_VIEWER_URL=http://${DEV_HOST}:${NGINX_PORT1}/openapi-viewer/
      - OPENAPI_VIEWER_V2=true

  #####
  # optional services
  #####

  events:
    profiles:
      - dev
    image: ghcr.io/data-fair/events:main
    network_mode: host
    environment:
      - PORT=${EVENTS_PORT}
      - MONGO_URL=mongodb://localhost:${MONGO_PORT}/data-fair-events
      - PRIVATE_DIRECTORY_URL=http://${DEV_HOST}:${NGINX_PORT1}/simple-directory
      - SECRET_IDENTITIES=secret-identities
      - SECRET_EVENTS=secret-events
      - SECRET_SENDMAILS=secret-sendmails
      - OBSERVER_ACTIVE=false

  openapi-viewer:
    profiles:
      - dev
    image: ghcr.io/data-fair/openapi-viewer:master
    network_mode: host
    environment:
      - PORT=${OAV_PORT}
      - USE_SIMPLE_DIRECTORY=true
      - ALLOWED_URLS={"processings":"http://${DEV_HOST}:${NGINX_PORT1}/processings/api/v1/api-docs.json","processingsId":"http://${DEV_HOST}:${NGINX_PORT1}/processings/api/v1/processings/{id}/api-docs.json","processingsAdmin":"http://${DEV_HOST}:${NGINX_PORT1}/processings/api/v1/admin/api-docs.json"}

  #####
  # db and search engine
  #####

  elasticsearch:
    profiles:
      - dev
    image: ghcr.io/data-fair/elasticsearch:7.x
    ports:
      - ${ES_PORT}:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_HEAP_SIZE=128m
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m -server"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      start_period: 10s
      timeout: 5s
      interval: 2s
      retries: 50

  mongo:
    profiles:
      - dev
    image: mongo:4.2
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongo-data:/data/db

  #####
  # Api and worker in docker mode
  #####

  main:
    build:
      context: .
      dockerfile: Dockerfile
      target: main
      args:
        NODE_ENV: development
    depends_on:
      - data-fair
    profiles:
      - testImages
    image: datafair/processings/main:dev
    network_mode: host
    environment:
      - NODE_ENV=development
    volumes:
      - processings-data:/app/data

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
      args:
        NODE_ENV: development
    depends_on:
      - data-fair
    profiles:
      - testImages
    image: datafair/processings/worker:dev
    network_mode: host
    environment:
      - NODE_ENV=development
    volumes:
      - processings-data:/app/data

volumes:
  elasticsearch-data:
  mongo-data:
  processings-data:
