version: '3'
services:
  sd:
    image: koumoul/simple-directory:2
    network_mode: host
    environment:
      - ADMINS=["superadmin@test.com"]
      - PUBLIC_URL=http://localhost:5600/simple-directory
      - MAILDEV_ACTIVE=true
      - STORAGE_TYPE=file
      - NO_UI=${NO_UI}
      - AUTHRATELIMIT_ATTEMPTS=200
    volumes:
      - ./test/resources/users.json:/webapp/data/users.json
      - ./test/resources/organizations.json:/webapp/data/organizations.json

  data-fair:
    image: koumoul/data-fair:master
    restart: on-failure:10
    network_mode: host
    environment:
      - PORT=8081
      - DEBUG=files
      - MONGO_URL=mongodb://localhost:27017/data-fair
      - OPENAPI_VIEWER_URL=http://localhost:5600/openapi-viewer/
      - DIRECTORY_URL=http://localhost:5600/simple-directory
      - PUBLIC_URL=http://localhost:5600/data-fair
      - WS_PUBLIC_URL=ws://localhost:5600/data-fair
      - EXTRA_NAV_ITEMS=[{"id":"processings","can":"contrib","iframe":"http://localhost:5600/embed/processings","icon":"mdi-cog-transfer-outline","title":"Traitements périodiques"}]
      - EXTRA_ADMIN_NAV_ITEMS=[{"id":"processings","iframe":"http://localhost:5600/","icon":"mdi-cog-transfer-outline","title":"Traitements périodiques"}]

  elasticsearch:
    image: koumoul/data-fair-elasticsearch:latest
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node

  mongo:
    image: mongo:4.1
    ports:
      - 27017:27017
