version: '3'
services:
  #####
  # reverse proxy for the whole environment
  #####
  nginx:
    image: nginx:1.23.1-alpine
    network_mode: host
    volumes:
      - ./dev/resources/nginx.conf:/etc/nginx/nginx.conf:ro

  #####
  # related services from the data-fair stack
  #####
  simple-directory:
    profiles:
      - dev
      - test
    image: ghcr.io/data-fair/simple-directory:master
    network_mode: host
    environment:
      - ADMINS=["superadmin@test.com"]
      - PUBLIC_URL=http://localhost:5600/simple-directory
      - MAILDEV_ACTIVE=true
      - STORAGE_TYPE=file
      - NO_UI=${NO_UI}
      - AUTHRATELIMIT_ATTEMPTS=200
      - PROMETHEUS_ACTIVE=false
      - MANAGE_PARTNERS=true
    volumes:
      - ./test/resources/users.json:/webapp/data/users.json
      - ./test/resources/organizations.json:/webapp/data/organizations.json

  data-fair:
    profiles:
      - dev
      - test
    image: ghcr.io/data-fair/data-fair:master
    restart: on-failure:10
    network_mode: host
    depends_on:
      - simple-directory
      - mongo
    environment:
      - PORT=8081
      - DEBUG=files
      - MONGO_URL=mongodb://localhost:27017/data-fair
      - OPENAPI_VIEWER_URL=http://localhost:5600/openapi-viewer/
      - DIRECTORY_URL=http://localhost:5600/simple-directory
      - PUBLIC_URL=http://localhost:5600/data-fair
      - WS_PUBLIC_URL=ws://localhost:5600/data-fair
      - EXTRA_NAV_ITEMS=[{"id":"processings","can":"contrib","iframe":"http://localhost:5600/embed/processings","icon":"mdi-cog-transfer-outline","title":"Traitements périodiques"}]
      - EXTRA_ADMIN_NAV_ITEMS=[{"id":"processings","iframe":"http://localhost:5600/","icon":"mdi-cog-transfer-outline","title":"Traitements périodiques"}]
      - OBSERVER_ACTIVE=false
    volumes:
      - data-fair-data:/data

  elasticsearch:
    profiles:
      - dev
      - test
    image: ghcr.io/data-fair/elasticsearch:7.x
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      timeout: 10s
      interval: 2s
      retries: 50

  mongo:
    profiles:
      - dev
      - test
    image: mongo:4.1
    ports:
      - 27017:27017

  notify:
    profiles:
      - dev
    image: ghcr.io/data-fair/notify:master
    network_mode: host
    environment:
      - PORT=8088
      - PUBLIC_URL=http://localhost:5600/notify
      - WS_PUBLIC_URL=ws://localhost:5600/notify
      - DIRECTORY_URL=http://localhost:5600/simple-directory
      - SECRET_NOTIFICATIONS=secret-notifications
      - SECRET_SENDMAILS=secret-sendmails
      - PROMETHEUS_ACTIVE=false

volumes:
  elasticsearch-data:
  mongo-data:
  data-fair-data: