/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LayoutActions: typeof import('./../src/components/layout/layout-actions.vue')['default']
    LayoutActionsButton: typeof import('./../src/components/layout/layout-actions-button.vue')['default']
    LayoutActionsRight: typeof import('./../src/components/layout/layout-actions-right.vue')['default']
    PrivateAccess: typeof import('./../src/components/private-access.vue')['default']
    ProcessingActions: typeof import('./../src/components/processing/processing-actions.vue')['default']
    ProcessingActivity: typeof import('./../src/components/processing/processing-activity.vue')['default']
    ProcessingCard: typeof import('./../src/components/processing/processing-card.vue')['default']
    ProcessingRuns: typeof import('./../src/components/processing/processing-runs.vue')['default']
    ProcessingsActions: typeof import('./../src/components/processings-actions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunListItem: typeof import('./../src/components/run/run-list-item.vue')['default']
    RunLogsList: typeof import('./../src/components/run/run-logs-list.vue')['default']
  }
}
