name: Build CI

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-api:
    uses: ./.github/workflows/main-build.yml
    with:
      workspace: api

  build-worker:
    uses: ./.github/workflows/main-build.yml
    with:
      workspace: worker

  build-ui:
    uses: ./.github/workflows/main-build.yml
    with:
      workspace: ui
